### ISSUE TITLE
e2e tests fail: Timed out waiting for asynchronous Angular tasks to finish

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/ketohub_web_app#194]
I'm trying to get my e2e tests running, but I'm seeing errors when trying to launch a simple E2E test.

My [first attempt](https://github.com/mtlynch/ketohub_web_app/pull/191) uses protractor@5.0.0 because that's the last version where `webdriver-update start --detach` worked, but then it seems like if I use that version, it can’t recognize HeadlessChrome:

```
E/launcher - unknown error: unrecognized Chrome version: HeadlessChrome/63.0.3239.84
```
https://travis-ci.org/mtlynch/ketohub_web_app/builds/325175045

My [second attempt](https://github.com/mtlynch/ketohub_web_app/pull/192) fails with "Timed out waiting for asynchronous Angular tasks to finish."

```
[15:15:45] I/update - chromedriver: file exists /home/mike/web_app/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.34.zip
[15:15:45] I/update - chromedriver: unzipping chromedriver_2.34.zip
[15:15:45] I/update - chromedriver: setting permissions to 0755 for /home/mike/web_app/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.34
[15:15:45] I/update - chromedriver: chromedriver_2.34 up to date
[15:15:45] I/launcher - Running 1 instances of WebDriver
[15:15:45] I/direct - Using ChromeDriver directly...
Jasmine started

  ketohub App
    ✗ should have right title
      - Failed: Timed out waiting for asynchronous Angular tasks to finish after 11 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
        (Session info: headless chrome=63.0.3239.84)
        (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-62-generic x86_64)
          at Object.checkLegacyResponse (/home/mike/web_app/node_modules/selenium-webdriver/lib/error.js:546:15)
          at parseHttpResponse (/home/mike/web_app/node_modules/selenium-webdriver/lib/http.js:509:13)
          at doSend.then.response (/home/mike/web_app/node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
      From: Task: Protractor.waitForAngular()
          at Driver.schedule (/home/mike/web_app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
          at ProtractorBrowser.executeAsyncScript_ (/home/mike/web_app/node_modules/protractor/built/browser.js:425:28)
          at angularAppRoot.then (/home/mike/web_app/node_modules/protractor/built/browser.js:456:33)
          at ManagedPromise.invokeCallback_ (/home/mike/web_app/node_modules/selenium-webdriver/lib/promise.js:1376:14)
          at TaskQueue.execute_ (/home/mike/web_app/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/home/mike/web_app/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at asyncRun (/home/mike/web_app/node_modules/selenium-webdriver/lib/promise.js:2927:27)
          at /home/mike/web_app/node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
      From: Task: Run it("should have right title") in control flow
          at UserContext.<anonymous> (/home/mike/web_app/node_modules/jasminewd2/index.js:94:19)
          at /home/mike/web_app/node_modules/jasminewd2/index.js:64:48
          at ControlFlow.emit (/home/mike/web_app/node_modules/selenium-webdriver/lib/events.js:62:21)
          at ControlFlow.shutdown_ (/home/mike/web_app/node_modules/selenium-webdriver/lib/promise.js:2674:10)
          at shutdownTask_.MicroTask (/home/mike/web_app/node_modules/selenium-webdriver/lib/promise.js:2599:53)
          at MicroTask.asyncRun (/home/mike/web_app/node_modules/selenium-webdriver/lib/promise.js:2728:9)
          at /home/mike/web_app/node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
      From asynchronous test:
      Error
          at Suite.<anonymous> (/home/mike/web_app/e2e/app.e2e-spec.ts:11:3)
          at Object.<anonymous> (/home/mike/web_app/e2e/app.e2e-spec.ts:3:1)
          at Module._compile (module.js:643:30)
          at Module.m._compile (/home/mike/web_app/node_modules/ts-node/src/index.ts:392:23)
          at Module._extensions..js (module.js:654:10)
          at Object.require.extensions.(anonymous function) [as .ts] (/home/mike/web_app/node_modules/ts-node/src/index.ts:395:12)
          at Module.load (module.js:556:32)
          at tryModuleLoad (module.js:499:12)
          at Function.Module._load (module.js:491:3)
          at Module.require (module.js:587:17)
          at require (internal/module.js:11:18)

**************************************************
*                    Failures                    *
**************************************************

1) ketohub App should have right title
  - Failed: Timed out waiting for asynchronous Angular tasks to finish after 11 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular

Executed 1 of 1 spec (1 FAILED) in 12 secs.
[15:15:58] I/launcher - 0 instance(s) of WebDriver still running
[15:15:58] I/launcher - chrome #01 failed 1 test(s)
[15:15:58] I/launcher - overall: 1 failed spec(s)
[15:15:58] E/launcher - Process exited with error code 1
```

https://travis-ci.org/mtlynch/ketohub_web_app/builds/325594808

**Comment by prohorova** [comment]
angular/protractor#4300
